baseURL = 'https://christina23.github.io/sourdough/'
languageCode = 'en-us'
title = "Let's Make Sourdough"
theme = 'ananke'

[params]
  description = "Everything you need to know to make a starter, bake your first loaf, and keep your starter alive."
  favicon = "/sourdough/favicon.svg"
  background_color_class = "bg-camel"

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3
