baseURL = 'https://christina23.github.io/sourdough/'
languageCode = 'en-us'
title = 'Sourdough Guide'
theme = 'ananke'

[params]
  description = "Everything you need to know to bake your first sourdough loaf."

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3
